### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by biancacristinaalves** [biancacristinaalves/SAP006-data-lovers#18]
- [x]  UI: É *responsivo*. (que reage de forma esperada)
- [x]  Usar VanillaJS.
- [x]  Não utilizar `this`.
- [x]  UI: Mostra lista/tabela/etc com dados e/ou indicadores.
- [x]  UI: Permite ordenar dados por um ou mais campos (asc e desc).
- [x]  UI: Permite filtrar dados com base em uma condição.
